# Ensure relevant APT keys are present on the system to support extra repositories added later.
- name: Add apt keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: '{{item}}'
  loop:
    - '8FD3D9A8D3800305A9FFF259D1742AD60D811D58' # Spotify
    - '4CCA1EAF950CEE4AB83976DCA040830F7FAC5991' # Google-1
    - 'EB4C1BFD4F042F6DDDCCEC917721F63BD38B4796' # Google-2
    - '1302DE60231889FE1EBACADC54678CF75A278D9C' # VS Codium
  become: true

# Enable extra repositories needed on the system. Mostly development, productivity etc.
- name: Enable extra Debian repos
  apt_repository: filename='{{item.file}}' repo='{{item.repo}}' state=present
  loop:
    - {file: 'spotify', repo: 'deb http://repository.spotify.com stable non-free'} # HTTP :(
    - {file: 'google-chrome', repo: 'deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main'}
    - {file: 'vscodium', repo: 'deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main'}
  become: true

- name: Ensure packages from PPA
  package: name='{{item}}' state=latest
  loop:
    - openvpn
    - filezilla
    - vlc
    - gimp
    - inkscape
    - spotify-client
    - google-chrome-stable
    - codium
    - guake
    - liblua5.3-dev
    - libcurl4-gnutls-dev
    - libarchive-dev
    - libssh-dev
    - libgit2-dev
    - openjdk-11-jdk
    - gir1.2-gtop-2.0
    - gir1.2-nm-1.0
    - gir1.2-clutter-1.0
  become: true
# wine winetricks steam

# - name: Create temporary directory for binary downloads
#   become: yes
#   tempfile:
#     state: directory
#     suffix: profile-binaries
#   register: temp_bins
  
# - name: Download Binaries for custom packages
#   become: yes
#   get_url: url='{{item.url}}' dest='{{item.dest}}'
#   loop:
#     - {url: "https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US", dest: "{{ temp_bins }}"}
#   register: bin_files

# - name: Download and extract additional packages
#   become: yes
#   unarchive: src='{{item.src}}' dest='{{item.dest}}' mode='{{item.mode}}' remote_src='{{item.remote_src}}'
#   loop:
#     - src: "https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US"
#       dest: "{{ temp_bins }}"
#       mode: preserve
#       remote_src: yes
