- import_tasks: debian.yml
  when: ansible_os_family == "Debian"
- import_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- import_tasks: viber.yml
  when: ansible_os_family == 'Debian' and profile_viber_install == true

# Ensure own user settings
- name: Update own {{host_username}}
  user:
    name: '{{host_username}}'
    shell: /bin/zsh
    append: yes
  become: true

- name: Link themes folder
  file:
    src: "{{ dotfiles_home }}/roles/profile/files/themes"
    dest: "{{ dotfiles_user_home }}/.local/share/themes"
    state: link
    force: yes

# TODO https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb