- hosts: localhost
  gather_facts: yes
  become: false
  tasks:
  - name: OS family
    debug: msg="{{ ansible_os_family }}"
  - name: Distribution
    debug: msg="{{ ansible_distribution }}"
  - name: Distribution Release
    debug: msg="{{ ansible_distribution_release }}"
    
  - name: Ansible Architecture
    debug: msg="{{ ansible_architecture}}"
  # - name: Distribution major version
  #   debug: msg="{{ ansible_distribution_major_version }}"
  # - name: Print all available facts
  #   debug:
  #     var: ansible_facts
