---
roles:
- geerlingguy.docker
- geerlingguy.php
- geerlingguy.composer
- geerlingguy.php-xdebug
- oefenweb.virtualbox
- oefenweb.slack
- petermosmans.customize-gnome
- name: darkwizard242.keybase
  src: https://github.com/punkch/ansible-role-keybase
  version: master
- name: punkch.nvm
  src: https://github.com/punkch/ansible-role-nvm
  version: master
- name: marvel-nccr.python
  src: https://github.com/punkch/ansible-role-python
  version: master
- diodonfrost.terraform
- geerlingguy.helm
- fubarhouse.golang
