- name: codium | install dependencies (apt)
  become: yes
  apt:
    name:
      - ca-certificates
      - apt-transport-https
      - gconf2
      - libasound2
      - libgtk2.0-0
      - libxss1
      - libxcb-dri3-0
      - libdrm2
      - libgbm1
      - libxshmfence1
    state: present
  when: ansible_distribution != "Parrot"


- name: codium | Add apt keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: '1302DE60231889FE1EBACADC54678CF75A278D9C'
  become: true
  when: ansible_distribution != "Parrot"

- name: codium | Install Codium repo (apt)
  become: yes
  apt_repository:
    repo: 'deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main'
    filename: vscodium
    state: present
  when: ansible_distribution != "Parrot"

- name: codium | Install Codium (apt)
  become: yes
  apt:
    name: "{{ codium_package_name }}{{ (codium_package_version | length > 0) | ternary('=' + codium_package_version, '') }}"
    state: present