- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: codium | Install extensions
  become: yes
  become_user: '{{ item.0.username }}'
  codium_install_extension:
    executable: '{{ codium_executable }}'
    name: '{{ item.1 }}'
  with_subelements:
    - '{{ codium_users }}'
    - extensions
    - skip_missing: yes
  loop_control:
    label: '{{ item.0.username }}: {{ item.1 }}'

- name: codium | Create config directories for users
  become: yes
  become_user: '{{ user.username }}'
  file:
    path: '~{{ user.username }}/{{ codium_config_path }}'
    state: directory
    mode: 'u=rwx,go=rx'
  with_items: '{{ codium_users }}'
  loop_control:
    loop_var: user
    label: '{{ user.username }}'
  when: "user.settings is defined and user.settings not in ({}, '', None, omit)"

- name: codium | Create settings directory
  become: yes
  become_user: '{{ user.username }}'
  file:
    path: '~{{ user.username }}/{{ codium_config_path }}/User'
    state: directory
    mode: 'u=rwx,go='
  with_items: '{{ codium_users }}'
  loop_control:
    loop_var: user
    label: '{{ user.username }}'
  when: "user.settings is defined and user.settings not in ({}, '', None, omit)"

- name: codium | Write settings
  become: yes
  become_user: '{{ user.username }}'
  template:
    src: settings.json.j2
    dest: "~{{ user.username }}/{{ codium_config_path }}/User/settings.json"
    force: "{{ user.settings_overwrite | default(False) | bool }}"
    mode: 'u=rw,go='
  with_items: '{{ codium_users }}'
  loop_control:
    loop_var: user
    label: '{{ user.username }}'
  when: "user.settings is defined and user.settings not in ({}, '', None, omit)"

- name: codium | Write keybindings
  become: yes
  become_user: '{{ user.username }}'
  template:
    src: keybindings.json.j2
    dest: "~{{ user.username }}/{{ codium_config_path }}/User/keybindings.json"
    force: "{{ user.keybindings_overwrite | default(False) | bool }}"
    mode: 'u=rw,go='
  with_items: '{{ codium_users }}'
  loop_control:
    loop_var: user
    label: '{{ user.username }}'
  when: "user.keybindings is defined and user.keybindings not in ({}, '', None, omit)"
