- name: gcloud | Ensure download path exists
  file: path={{ gcloud_archive_path }} state=directory

- name: gcloud | Extract Cloud SDK archive
  unarchive:
    src: "{{ gcloud_archive_url }}"
    dest: "{{ gcloud_archive_path }}"
    remote_src: yes
    creates: "{{ gcloud_library_path }}"

- name: gcloud | Install Components
  command: >-
    {{ gcloud_library_path }}/install.sh --quiet
    --usage-reporting {{ gcloud_usage_reporting | lower }}
    {% if gcloud_override_components | length > 0 %}--override-components
      {% for component in gcloud_override_components %}{{ component }}
        {% if loop.index < gcloud_override_components | length  %}
        {% endif %}
      {% endfor %}
    {% endif %}
    {% if gcloud_additional_components | length > 0 %}--additional-components
      {% for component in gcloud_additional_components %}{{ component }}
        {% if loop.index < gcloud_additional_components | length %}
        {% endif %}
      {% endfor %}
    {% endif %}
